apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular12angular12webapp
  labels:
    app: angular12-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      service: angular12webapp
  template:
    metadata:
      labels:
        app: angular12-demo
        service: angular12webapp
    spec:
      containers:
        - name: angular12webapp
          image: romancadete/angular12kubernetes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: angular12webapp
  labels:
    app: angular12-demo
    service: angular12webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: angular12webapp